export type Lang = "hi" | "en";

export const CONTACT = {
  phoneDisplay: "+91 87701 72634",
  phoneIntl: "918770172634",
  email: "dr.mohittawar@gmail.com",
  instagram: "https://instagram.com/yogagurudrmohit",
  youtube: "https://youtube.com/@yogagurudrmohit",
  justdial: "https://jsdl.in/DT-17TQXCYHTUS",
  city: "Bhopal, Madhya Pradesh, India",
  googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Yoga+Guru+Dr+Mohit+Bhopal",
};

export const BILINGUAL_CONTENT = {
  en: {
    topBanner: {
      left: "Guinness World Record Holder • Ph.D. Yogic Science • BHMS Homeopathy",
      right: "Clinical Sanctuary in Bhopal & Global Virtual Mentorship",
    },
    nav: {
      brandSub: "Celebrity Yoga Expert • Ph.D.",
      philosophy: "Philosophy",
      protocols: "Clinical Therapeutics",
      pacer: "Prana Bio-Pacer",
      credentials: "Qualifications",
      gallery: "Hall of Recognition",
      pricing: "Pricing",
      reviews: "Reviews",
      consultation: "Consultation",
      bookBtn: "Book Session",
      langSwitch: "हिन्दी में पढ़ें",
    },
    hero: {
      badge: "Guinness World Record Holder in Yoga",
      titleMain: "Harmonize Body,",
      titleAccent: "Master Mind",
      subtitle:
        "Dr. Mohit Tawar has a Ph.D. in Yoga and a Guinness World Record. For over a decade, he has helped people heal naturally through yoga — for back pain, stress, prostate health, and more.",
      ctaPrimary: "Book a Consultation",
      ctaSecondary: "Try the Breathing Exercise",
      statusLive: "In Meditation",
      record1Title: "Guinness World Record",
      record1Sub: "Yoga Endurance",
      record2Title: "Ph.D. in Yoga",
      record2Sub: "Doctorate in Yogic Science",
      record3Title: "India Book of Records",
      record3Sub: "Kukkutasana Pose",
      rhythmLabel: "Breathing Rhythm: 4-4-6-2s",
    },
    pacer: {
      tag: "Somatic Vagus Nerve Calibration",
      title: "Bhramari & Antar Kumbhaka Pacer",
      desc: "Based on Dr. Mohit Tawar's clinical research: the 136.1 Hz natural humming vibration produces rapid nitric oxide diffusion in the cranial and nasal sinuses, down-regulating cortisol and normalizing arterial pressure within 3 to 5 minutes.",
      steps: [
        { num: "1", text: "Gently press the ear tragus inward with your index fingers to seal auditory distraction." },
        { num: "2", text: "Deeply draw Prana through nostrils into the lower abdomen as the solar ring expands." },
        { num: "3", text: "During exhalation, produce a resonant bee-humming (Bhramari) sound at the soft palate." },
      ],
      btnStart: "Begin Daily Calibration",
      btnPause: "Pause Sequence",
      audioActive: "136.1Hz Harmonic Tone Active",
      audioMuted: "Soundtrack Muted",
      recommended: "Clinical Dose: 5 to 11 Consecutive Cycles at Dawn or Twilight",
      inhale: "Inhale (Purak)",
      hold: "Antar Kumbhaka (Hold)",
      exhale: "Bhramari & Rechak (Humming)",
      rest: "Shunya Rest (Neutral)",
      inhaleSub: "Diaphragmatic Expansion",
      holdSub: "Prana Lock in Core",
      exhaleSub: "136.1Hz Vagus Tone",
      restSub: "Stillness & Centering",
      presets: [
        { id: "stress", label: "Stress Relief", inhale: 4, hold: 4, exhale: 6, rest: 2 },
        { id: "bp", label: "BP Balance", inhale: 5, hold: 5, exhale: 7, rest: 2 },
        { id: "sleep", label: "Sleep Reset", inhale: 4, hold: 7, exhale: 8, rest: 2 },
      ],
      videoCaption: "Guided Bhramari breathing demonstration",
    },
    protocols: {
      tag: "Integrative Clinical Therapeutics",
      title: "Targeted Yogic Organ Restoration",
      subtitle:
        "Bridging BHMS homeo-pathology and Hatha Yoga bandha mechanics. Documented natural recoveries avoiding surgery.",
      exploreBtn: "Consult on this Protocol",
      mentorshipBadge: "Cohort Capacity: Max 20 Seekers",
      shastraHeader: "Shastric Scriptural Anchor",
      disclaimer:
        "Educational & therapeutic guidance only — not a substitute for professional medical diagnosis. If you have a diagnosed condition, consult a physician before beginning any protocol.",
      items: [
        {
          id: "uterus-prolapse",
          tabTitle: "Uterine Prolapse",
          title: "Uterine Prolapse (Garbhashaya Bhransha) Recovery",
          subtitle: "Non-Surgical Pelvic Elevation & Apana Vayu Inversion",
          views: "1.7M+ Clinically Benefited",
          summary:
            "A specialized sequence utilizing controlled pelvic inversions, passive bolster elevations, and rhythmic Ashwini Mudra contractions to tone stretched pubococcygeus ligaments and reverse Stage I & II pelvic descent.",
          points: [
            "Passive inverted alignments that immediately alleviate downward gravimetric pressure",
            "Targeted transverse abdominis and levator ani neuromuscular activation",
            "Mula Bandha lock paired with progressive retention (Kumbhaka)",
            "Complementary homeopathic dietary and bio-tissue cellular nutrition",
          ],
          quote:
            "When Apana Vayu is drawn upwards through Viparita Karani and Ashwini pulsation, the pelvic floor regains its natural buoyancy without surgical intervention.",
          quoteRef: "Hatha Yoga Pradipika & Clinical Case Study (Dr. Mohit Tawar)",
        },
        {
          id: "prostate-pelvic",
          tabTitle: "Prostate & Urinary Health",
          title: "Prostate Hypertrophy & Pelvic Floor Tonic",
          subtitle: "7 Foundational Asanas & Apana Stagnation Decongestion",
          views: "850K+ Practitioners",
          summary:
            "Designed specifically for benign prostatic hypertrophy, nocturnal urine frequency, and vascular congestion in the perineum through targeted hip abduction and arterial flow stimulation.",
          points: [
            "Baddha Konasana variations with micro-pelvic oscillations",
            "Gomukhasana and Setu Bandha for pelvic venous drainage",
            "Chandra Nadi and Shitali Pranayama to cool excessive localized heat (Pitta)",
            "Apana Mudra conditioning during twilight circadian intervals",
          ],
          quote:
            "Decongesting the root plexus (Muladhara) restores cellular vitality and normalizes urinary sphincter tension.",
          quoteRef: "Yoga Vashistha & Clinical Observations",
        },
        {
          id: "kukkutasana-balance",
          tabTitle: "Kukkutasana Mastery",
          title: "Kukkutasana & Core Vacuum Dynamics",
          subtitle: "National Gold Lineage & India Book of Records Technique",
          views: "Guinness Record Distinction",
          summary:
            "The definitive masterclass in Cockerel Pose mechanics: hip external rotation, carpometacarpal tendon fortification, and Uddiyana Bandha abdominal levitation.",
          points: [
            "Safe anatomical prep for tight hip flexors and deep Lotus seat",
            "Weight dispersal physics across the ten metacarpal finger nodes",
            "Agni Sara kriya to build core vacuum levitation force",
            "Sustained balance endurance without carpal tunnel strain",
          ],
          quote:
            "The rooster pose is not muscular force; it is the complete stillness of mind channeled through the palms.",
          quoteRef: "Gheranda Samhita II:31",
        },
        {
          id: "hasta-mudra",
          tabTitle: "Hasta Mudra Vigyan",
          title: "Hasta Mudra Vigyan (Neuro-Elemental Reflexology)",
          subtitle: "Balancing the 5 Pranic Elements via Digital Terminal Points",
          views: "International Practice",
          summary:
            "Hand mudras act as precise electromagnetic switches in the nervous system. Dedicated protocols for joint synovial lubrication (Sandhi Mudra), cellular energy (Prana Mudra), and mental focus (Kuber Mudra).",
          points: [
            "Sandhi Mudra: Vayu & Earth finger conjunction to stimulate joint fluid renewal",
            "Prithvi Mudra: Restoring tissue density, vitamin absorption, and physical stability",
            "15 to 45 minute continuous holds synchronized with solar circadian prahars",
            "Neurological biofeedback stimulating pituitary-hypothalamus harmony",
          ],
          quote:
            "The five fingers represent the five cosmic mahabhutas. By closing their circuit, inner pathology dissolves.",
          quoteRef: "Mudra Vigyan Shastra",
        },
      ],
    },
    credentials: {
      tag: "Academic Pedigree & Honors",
      title: "A Confluence of High Science & Himalayan Authenticity",
      desc: "Dr. Mohit Tawar bridges university doctorate research with living yogic sadhana. As an Associate Professor in Yoga and practicing Homeopath, his approach to wellness is diagnostic, humane, and deeply transformative.",
      qualTitle: "Doctoral & Clinical Accreditations",
      cityTag: "Bhopal, Madhya Pradesh • Senior Faculty & Physician",
      list: [
        {
          degree: "Ph.D. in Yoga (विद्यावाचस्पति)",
          desc: "Advanced doctoral dissertation on psychosomatic homeostasis, therapeutic pranayama, and organ biomechanics.",
        },
        {
          degree: "M.Sc. Human Consciousness & Yogic Science",
          desc: "Trained at State Government University with apex distinction in higher classical texts and anatomy.",
        },
        {
          degree: "B.H.M.S. & PG N.A.H.I. (Nagpur)",
          desc: "Licensed Homeopathic physician, seamlessly uniting organic pathology with therapeutic rehabilitation.",
        },
        {
          degree: "PG Diploma in Vastu & Medical Jyotish",
          desc: "Harmonizing environmental energetic fields, circadian bio-rhythms, and elemental astrology.",
        },
      ],
      records: [
        { title: "Guinness World Record", desc: "Recognized internationally for exceptional yogic endurance and breath mastery." },
        { title: "India Book of Records", desc: "Official record holder in Kukkutasana (Cockerel Pose) sustained stationary elevation." },
        { title: "National & International Gold", desc: "Multiple gold medals representing India across premier yogic championship circuits." },
        { title: "Associate Professor in Yoga", desc: "Mentoring undergraduate and post-graduate scholars, grooming the next generation of yoga physicians." },
      ],
      stats: [
        { num: "482K+", label: "Instagram Followers" },
        { num: "51.8K+", label: "YouTube Subscribers" },
        { num: "2,000+", label: "Authentic Yoga Lessons" },
        { num: "100%", label: "Shastric Fidelity" },
      ],
    },
    gallery: {
      tag: "Verified Lineage & Media",
      title: "Hall of Recognition",
      subtitle: "Sessions, students, and milestones from Dr. Mohit Tawar's clinical practice and public yogic service.",
      items: [
        { image: "/images/teaching-session.png", caption: "One-on-one therapeutic session, Bhopal studio" },
        { image: "/images/group-class.png", caption: "Outdoor Vrikshasana group practice" },
        { image: "/images/kukkutasana-record.jpg", caption: "Record-distinction Kukkutasana biomechanics" },
      ],
      socialCta: "Follow the full archive of 2,000+ sessions",
    },
    pricing: {
      tag: "Class Packages",
      title: "Yoga Class Packages",
      subtitle: "Pick a package and order directly on WhatsApp — Dr. Mohit Tawar's team will confirm your slot.",
      orderBtn: "Order on WhatsApp",
      closingCta: "Looking for something else? Message Dr. Mohit Tawar directly.",
      closingBtn: "Message on WhatsApp",
      plans: [
        {
          id: "online-offline",
          title: "Online & Offline Yoga Classes",
          desc: "Monsoon special — basic to advance yoga, power yoga, weight-loss yoga, pranayama & meditation.",
          price: "₹500",
          originalPrice: "₹1,000",
          badge: "50% OFF",
        },
        {
          id: "yoga-class",
          title: "Yoga Class",
          desc: "Power Yoga, Advance Yoga, Pranayama. Monday–Friday, 6 AM & 7 PM batches.",
          price: "₹1,500",
          originalPrice: "",
          badge: "",
        },
        {
          id: "personal-classes",
          title: "Personal Yoga Classes",
          desc: "One-on-one sessions directly with Dr. Mohit Kumar Tawar (BHMS, PhD in Yoga).",
          price: "₹15,000",
          originalPrice: "",
          badge: "",
        },
        {
          id: "any-condition",
          title: "Online Yoga for Any Health Condition",
          desc: "A tailored online yoga plan for whatever condition you're dealing with.",
          price: "₹500",
          originalPrice: "",
          badge: "",
        },
        {
          id: "divyanka-academy",
          title: "Divyanka Art Academy Yoga",
          desc: "Yoga sessions in partnership with Divyanka Art Academy.",
          price: "₹1,000",
          originalPrice: "",
          badge: "",
        },
      ],
    },
    reviews: {
      tag: "Verified Google Reviews",
      title: "What Students Say",
      subtitle: "Real reviews from Dr. Mohit Tawar's Google Business profile.",
      ratingValue: "5.0",
      ratingCount: "140 Google reviews",
      viewAllBtn: "Read all reviews on Google",
      ownerReplyLabel: "Owner reply:",
      items: [
        {
          name: "balkrishna karma",
          meta: "Local Guide · 22 reviews",
          time: "2 years ago",
          text: "Best yoga class. The teacher is an ayurvedic doctor, has a PhD in yoga, and also holds a Guinness World Record. Best one you can get in the town. Loved his classes — helped me improve my physical & mental health. Totally recommended!",
          ownerReply: "",
        },
        {
          name: "HARSH Maithil",
          meta: "14 reviews",
          time: "a year ago",
          text: "Amazing techniques of yoga — my back pain is completely gone. Mohit sir is an amazing yoga teacher, I'm loving it.",
          ownerReply: "",
        },
        {
          name: "pramila tawar",
          meta: "2 reviews",
          time: "2 years ago",
          text: "This yoga class was very helpful for me — my body weight decreased and muscle power increased. Thank you so much Dr. Mohit sir, a Guinness World Record holder in yoga and PhD in yoga, very knowledgeable personality.",
          ownerReply: "",
        },
        {
          name: "Aditya Barwal",
          meta: "1 review",
          time: "9 months ago",
          text: "Those 12–13 days of the MBBS journey were very beneficial and full of enjoyment. Thank you.",
          ownerReply: "Thank you",
        },
        {
          name: "Shweta Patidar",
          meta: "7 reviews · 1 photo",
          time: "9 months ago",
          text: "He is such a nice yoga guru, you will never realise when one hour passed on.",
          ownerReply: "",
        },
        {
          name: "Anup Singh",
          meta: "Local Guide · 63 reviews",
          time: "a year ago",
          text: "Best yoga expert. Gives good lessons which are beneficial for health. Well spoken and polite.",
          ownerReply: "",
        },
        {
          name: "Dr. Ravikant Gupta",
          meta: "1 review",
          time: "a year ago",
          text: "It's a very nice and informative yoga channel. Mohit sir is my favourite yoga instructor on YouTube — the classes and activities are very good.",
          ownerReply: "",
        },
        {
          name: "Vandit Jain",
          meta: "6 reviews · 7 photos",
          time: "2 years ago",
          text: "He teaches yoga very well. My back pain is completely gone too.",
          ownerReply: "",
        },
      ],
    },
    booking: {
      modalBadge: "Private Practice & Mentorship",
      modalTitle: "Consult With Dr. Mohit Tawar",
      modalSub: "Confidential evaluation for pelvic health, spine/joint disorders, or personalized sadhana.",
      fullName: "Full Name",
      phone: "WhatsApp Contact Number",
      city: "City & Country",
      topic: "Primary Area of Consultation",
      mode: "Consultation Mode",
      notes: "Health Concerns / Diagnostic Summary",
      submitBtn: "Send via WhatsApp",
      submitEmailBtn: "Or Email the Clinic",
      successTitle: "Namaste! Your Request Is Ready",
      successDesc: "WhatsApp has opened with your details prefilled — press Send there to reach Dr. Mohit Tawar's clinical team directly.",
      modes: ["In-Person Clinic Session (Bhopal Center)", "Virtual High-Definition Consultation (Global)"],
      disclaimer:
        "This form does not constitute an emergency medical service. For emergencies, please seek immediate local medical care.",
    },
    footer: {
      tagline: "Doctor of Yoga • Guinness World Record Holder • Bhopal, India",
      rights: "All Vedic therapeutic knowledge conserved with shastric sanctity.",
      contact: "Direct Clinic Inquiry: Bhopal, MP",
      addressLabel: "Clinic",
      phoneLabel: "WhatsApp / Phone",
      emailLabel: "Email",
    },
  },

  hi: {
    topBanner: {
      left: "गिनीज वर्ल्ड रिकॉर्ड धारक • योग में विद्यावाचस्पति (Ph.D.) • बी.एच.एम.एस. होम्योपैथ",
      right: "भोपाल क्लिनिक परामर्श एवं वैश्विक ऑनलाइन योग मार्गदर्शन",
    },
    nav: {
      brandSub: "सेलिब्रिटी योग विशेषज्ञ • एसोसिएट प्रोफेसर",
      philosophy: "दर्शन",
      protocols: "यौगिक चिकित्सा",
      pacer: "प्राणायाम अभ्यासक",
      credentials: "योग्यताएं व सम्मान",
      gallery: "सम्मान प्रभाग",
      pricing: "मूल्य सूची",
      reviews: "समीक्षाएं",
      consultation: "परामर्श",
      bookBtn: "परामर्श आरक्षित करें",
      langSwitch: "Read in English",
    },
    hero: {
      badge: "योग में गिनीज वर्ल्ड रिकॉर्ड धारक",
      titleMain: "शरीर को संतुलित करें,",
      titleAccent: "मन को शांत करें",
      subtitle:
        "डॉ. मोहित तवर के पास योग में पीएचडी और गिनीज वर्ल्ड रिकॉर्ड है। पिछले दस वर्षों से वे योग के ज़रिए लोगों को प्राकृतिक रूप से स्वस्थ रहने में मदद कर रहे हैं — कमर दर्द, तनाव, प्रोस्टेट स्वास्थ्य और अन्य समस्याओं में।",
      ctaPrimary: "परामर्श बुक करें",
      ctaSecondary: "श्वास अभ्यास करें",
      statusLive: "ध्यान में",
      record1Title: "गिनीज वर्ल्ड रिकॉर्ड",
      record1Sub: "योग सहनशक्ति",
      record2Title: "योग में पीएचडी",
      record2Sub: "योग विज्ञान में डॉक्टरेट",
      record3Title: "इंडिया बुक ऑफ रिकॉर्ड्स",
      record3Sub: "कुक्कुटासन मुद्रा",
      rhythmLabel: "श्वास लय: 4-4-6-2 सेकंड",
    },
    pacer: {
      tag: "वेगस तंत्रिका संतुलन एवं मानसिक शांति",
      title: "भ्रामरी एवं आंतर कुम्भक प्राणायाम",
      desc: "डॉ. मोहित तवर के शोध व शास्त्रीय अनुभव के अनुसार: भ्रामरी की 136.1 हर्ट्ज़ गुंजन ध्वनि से कपाल व नासिका गुहा में 'नाइट्रिक ऑक्साइड' का स्राव बढ़ता है, जिससे मानसिक तनाव, उच्च रक्तचाप एवं अनिद्रा में तत्काल शांति मिलती है।",
      steps: [
        { num: "1", text: "तर्जनी उंगली से दोनों कानों के छिद्रों को बंद करें ताकि बाह्य कोलाहल शांत हो सके।" },
        { num: "2", text: "नासिका से गहरी श्वास नाभि तक भरें जैसे ही यह स्वर्णिम चक्र फैलता है।" },
        { num: "3", text: "श्वास छोड़ते समय तालु से भंवरे की भांति 'म-कार' (ॐ) का मधुर व गहरा गुंजन करें।" },
      ],
      btnStart: "दैनिक अभ्यास प्रारंभ करें",
      btnPause: "अभ्यास रोकें",
      audioActive: "136.1 हर्ट्ज़ नाद सक्रिय",
      audioMuted: "ध्वनि बंद",
      recommended: "परामर्शित मात्रा: ब्रह्ममुहूर्त अथवा संध्या समय 5 से 11 चक्र",
      inhale: "पूरक (गहरी श्वास लें)",
      hold: "आंतर कुम्भक (श्वास रोकें)",
      exhale: "रेचक एवं भ्रामरी (गुंजन)",
      rest: "शून्य विश्राम (सहज ध्यान)",
      inhaleSub: "उदर व फेफड़ों का विस्तार",
      holdSub: "प्राण ऊर्जा का संचय",
      exhaleSub: "136.1Hz तंत्रिका विश्रांति",
      restSub: "परम शांति व समत्व",
      presets: [
        { id: "stress", label: "तनाव शमन", inhale: 4, hold: 4, exhale: 6, rest: 2 },
        { id: "bp", label: "रक्तचाप संतुलन", inhale: 5, hold: 5, exhale: 7, rest: 2 },
        { id: "sleep", label: "निद्रा पुनर्स्थापन", inhale: 4, hold: 7, exhale: 8, rest: 2 },
      ],
      videoCaption: "भ्रामरी श्वास प्रदर्शन वीडियो",
    },
    protocols: {
      tag: "विशिष्ट प्राकृतिक रोगोपचार",
      title: "प्रामाणिक यौगिक चिकित्सा प्रभाग",
      subtitle: "होम्योपैथिक विकृति विज्ञान और हठयोग के बंधों का समन्वय। बिना शल्य-चिकित्सा (ऑपरेशन) के अंगों की स्वाभाविक पुनर्स्थापना।",
      exploreBtn: "इस रोगोपचार हेतु परामर्श लें",
      mentorshipBadge: "सत्र क्षमता: केवल 20 साधक प्रति बैच",
      shastraHeader: "शास्त्रीय प्रमाण व संदर्भ",
      disclaimer:
        "यह जानकारी केवल शैक्षणिक व चिकित्सीय मार्गदर्शन हेतु है — यह चिकित्सक की सलाह का विकल्प नहीं है। यदि आपको कोई निदानित रोग है, तो अभ्यास प्रारंभ करने से पूर्व चिकित्सक से परामर्श अवश्य लें।",
      items: [
        {
          id: "uterus-prolapse",
          tabTitle: "बच्चेदानी खिसकना (प्रोलैप्स)",
          title: "गर्भाशय भ्रंश (Uterus Prolapse) का प्राकृतिक योगिक उपचार",
          subtitle: "अपान वायु का उर्ध्वगमन एवं श्रोणि पेशियों (Pelvic Floor) का सुदृढ़ीकरण",
          views: "17 लाख+ साधकों द्वारा लाभान्वित",
          summary:
            "गर्भाशय की शिथिलता (प्रथम व द्वितीय चरण) में बिना सर्जरी के अंग को ऊपर उठाने हेतु विपरीतकरणी, अश्विनी मुद्रा और विशिष्ट सूक्ष्म आसनों का वैज्ञानिक क्रम, जिससे पेल्विक स्नायु पुनः सशक्त होते हैं।",
          points: [
            "गुरुत्वाकर्षण के विपरीत तकिया/बोल्स्टर आधारित उत्थानासन विधियां",
            "पेल्विक फ्लोर (मूलाधार) की शिथिल मांसपेशियों में रक्त संचार की वृद्धि",
            "मूलबंध एवं कुम्भक द्वारा आंतरिक अंगों की प्राकृतिक लिफ्टिंग",
            "सहायक होम्योपैथिक दिनचर्या, पोषण एवं अपान वायु संशोधन",
          ],
          quote:
            "जब विपरीतकरणी और अश्विनी मुद्रा के अभ्यास से अपान वायु उर्ध्वगामी होती है, तो गर्भाशय बिना किसी कृत्रिम साधन के अपने स्वाभाविक स्थान पर स्थिर हो जाता है।",
          quoteRef: "हठप्रदीपिका एवं डॉ. मोहित तवर क्लिनिकल केस स्टडी",
        },
        {
          id: "prostate-pelvic",
          tabTitle: "प्रोस्टेट एवं पौरुष ग्रंथि",
          title: "पौरुष ग्रंथि वृद्धि (Prostate) एवं मूत्र विकार शमन",
          subtitle: "7 अचूक योगासन एवं मूलाधार चक्र शुद्धि",
          views: "8.5 लाख+ साधक",
          summary:
            "प्रोस्टेट ग्रंथि के बढ़ने, पेशाब रुकने या बार-बार आने की समस्या में पेल्विक क्षेत्र की सूजन कम करने और रक्त संचार सुगम बनाने के लिए शास्त्रीय आसनों की प्रमाणित श्रृंखला।",
          points: [
            "बद्धकोणासन एवं सूक्ष्म कटि चालन से ग्रंथियों का संकुचन निवारण",
            "गोमुखासन एवं सेतुबंधासन द्वारा श्रोणि शिराओं में शुद्ध रक्त संचार",
            "चंद्रनाड़ी व शीतली प्राणायाम द्वारा पित्त दोष एवं आंतरिक दाह का शमन",
            "अपान मुद्रा का नियमित अभ्यास, जो मूत्रमार्ग के अवरोध को दूर करता है",
          ],
          quote: "मूलाधार चक्र के शोधन और सुदृढ़ बंध अभ्यास से पौरुष ग्रंथि का प्रदाह शांत होता है और मूत्राशय का नियंत्रण वापस लौटता है।",
          quoteRef: "योग वशिष्ठ एवं क्लिनिकल अनुभव",
        },
        {
          id: "kukkutasana-balance",
          tabTitle: "कुक्कुटासन कीर्तिमान",
          title: "कुक्कुटासन एवं उड्डीयान बंध सिद्धि",
          subtitle: "इंडिया बुक ऑफ रिकॉर्ड्स धारक तकनीक एवं शारीरिक संतुलन",
          views: "गिनीज एवं राष्ट्रीय स्वर्ण पदक",
          summary:
            "हठयोग के अत्यंत कठिन कुक्कुटासन में दीर्घ समय तक शून्य में स्थिर रहने की तकनीक। कलाई, बाहु और पेट की आंतरिक पेशियों की अद्वितीय शक्ति का विज्ञान।",
          points: [
            "पद्मासन में जांघों और पिंडलियों के मध्य से बाहें निकालने की सूक्ष्म क्रिया",
            "दसों उंगलियों और हथेली पर शरीर के गुरुत्व केंद्र को साधने का भौतिकी नियम",
            "अग्निसार व उड्डीयान बंध के समन्वय से शरीर को हल्का (लघिमा) बनाना",
            "कलाइयों में बिना किसी खिंचाव या मोच के निरंतर संतुलन की कला",
          ],
          quote: "कुक्कुटासन केवल बाहुबल का प्रदर्शन नहीं, अपितु चित्त की पूर्ण एकाग्रता और प्राण शक्ति का हथेली पर संकेंद्रण है।",
          quoteRef: "घेरण्ड संहिता 2:31",
        },
        {
          id: "hasta-mudra",
          tabTitle: "हस्त मुद्रा विज्ञान",
          title: "हस्त मुद्रा विज्ञान (पंचतत्व संतुलन एवं नाड़ी तंत्र)",
          subtitle: "उंगलियों के चुंबकीय स्पर्श द्वारा असाध्य रोगों का शमन",
          views: "देश-विदेश में विख्यात",
          summary:
            "हाथ की पांचों उंगलियां पंचमहाभूतों (अग्नि, वायु, आकाश, पृथ्वी, जल) का प्रतिनिधित्व करती हैं। संधि मुद्रा (जोड़ों का दर्द), पृथ्वी मुद्रा (कमजोरी), और कुबेर मुद्रा (एकाग्रता) का शास्त्रीय प्रयोग।",
          points: [
            "संधि मुद्रा: वायु एवं पृथ्वी तत्व का मिलन, जो जोड़ों में चिकनाई (synovial fluid) बढ़ाता है",
            "पृथ्वी व आकाश मुद्रा: विटामिन व कैल्शियम की कमी दूर कर अस्थियों को दृढ़ बनाती हैं",
            "प्रतिदिन 15 से 45 मिनट तक निश्चित प्रहर में मुद्राओं का अभ्यास",
            "विद्युत-चुंबकीय ऊर्जा द्वारा मस्तिष्क के हाइपोथैलेमस को सक्रिय करना",
          ],
          quote: "करतले वर्तते विश्वं, मुद्रया सर्व सिध्यति। उंगलियों के सूक्ष्म विद्युत चक्र को जोड़ते ही शरीर की स्वतः-चिकित्सा शक्ति जागृत हो उठती है।",
          quoteRef: "मुद्रा विज्ञान शास्त्र",
        },
      ],
    },
    credentials: {
      tag: "अकादमिक प्रतिष्ठा एवं राष्ट्रीय सम्मान",
      title: "उच्चतम शोध और हिमालयी योग साधना का दुर्लभ संगम",
      desc: "डॉ. मोहित तवर पारंपरिक गुरु-शिष्य परंपरा के साथ-साथ विश्वविद्यालय स्तर के शोधकर्ता हैं। योग में एसोसिएट प्रोफेसर और पंजीकृत होम्योपैथिक चिकित्सक के रूप में उनका दृष्टिकोण पूर्णतः वैज्ञानिक एवं कल्याणकारी है।",
      qualTitle: "शैक्षणिक एवं चिकित्सीय उपाधियां",
      cityTag: "भोपाल, मध्य प्रदेश • प्राध्यापक एवं योग चिकित्सक",
      list: [
        { degree: "विद्यावाचस्पति (Ph.D.) - योग", desc: "मनो-शारीरिक संतुलन, चिकित्सीय प्राणायाम और आंतरिक अंगों के बायो-मैकेनिक्स पर सर्वोच्च शोध उपाधि।" },
        { degree: "एम.एससी. (मानव चेतना एवं योग विज्ञान)", desc: "शासकीय विश्वविद्यालय से प्रथम श्रेणी में हठयोग व उपनिषदों का गहन शास्त्रीय व प्रायोगिक अध्ययन।" },
        { degree: "बी.एच.एम.एस. एवं पी.जी. (नागपुर)", desc: "होम्योपैथिक चिकित्सा पद्धति के अधिकृत चिकित्सक, जो रोग निदान को योग के साथ समन्वित करते हैं।" },
        { degree: "पी.जी. डिप्लोमा - वास्तुशास्त्र एवं ज्योतिष", desc: "पर्यावरणीय ऊर्जा, दिशा संतुलन एवं जातक की ग्रह स्थिति के अनुसार स्वास्थ्य परामर्श।" },
      ],
      records: [
        { title: "गिनीज वर्ल्ड रिकॉर्ड धारक", desc: "अंतरराष्ट्रीय स्तर पर योग की कठिन विधाओं और श्वास नियंत्रण में विश्व कीर्तिमान।" },
        { title: "इंडिया बुक ऑफ रिकॉर्ड्स", desc: "कुक्कुटासन में निरंतर संतुलन और अद्वितीय शारीरिक उत्तोलन हेतु अधिकृत रिकॉर्ड।" },
        { title: "राष्ट्रीय व अंतरराष्ट्रीय स्वर्ण पदक", desc: "विभिन्न राष्ट्रीय योग चैंपियनशिप्स में मध्य प्रदेश और भारत का प्रतिनिधित्व करते हुए स्वर्ण पदक।" },
        { title: "एसोसिएट प्रोफेसर - योग", desc: "सैकड़ों छात्रों व शोधार्थियों को योग शिक्षक व योग चिकित्सक के रूप में प्रशिक्षित करने का अनुभव।" },
      ],
      stats: [
        { num: "4.8 लाख+", label: "इंस्टाग्राम परिवार" },
        { num: "51 हजार+", label: "यूट्यूब सब्सक्राइबर्स" },
        { num: "2,000+", label: "प्रामाणिक योग वीडियो" },
        { num: "100%", label: "शास्त्रीय प्रामाणिकता" },
      ],
    },
    gallery: {
      tag: "प्रामाणिक विरासत एवं मीडिया",
      title: "सम्मान प्रभाग",
      subtitle: "डॉ. मोहित तवर की क्लिनिकल प्रैक्टिस एवं सार्वजनिक योग सेवा के सत्र, साधक व उपलब्धियां।",
      items: [
        { image: "/images/teaching-session.png", caption: "व्यक्तिगत चिकित्सीय सत्र, भोपाल स्टूडियो" },
        { image: "/images/group-class.png", caption: "वृक्षासन समूह अभ्यास, प्रकृति के मध्य" },
        { image: "/images/kukkutasana-record.jpg", caption: "कुक्कुटासन कीर्तिमान बायोमैकेनिक्स" },
      ],
      socialCta: "2,000+ सत्रों का संपूर्ण संग्रह देखें",
    },
    pricing: {
      tag: "क्लास पैकेज",
      title: "योग क्लास पैकेज",
      subtitle: "अपना पैकेज चुनें और सीधे व्हाट्सएप पर ऑर्डर करें — डॉ. मोहित तवर की टीम आपका समय तय करेगी।",
      orderBtn: "व्हाट्सएप पर ऑर्डर करें",
      closingCta: "कुछ और चाहिए? डॉ. मोहित तवर को सीधे मैसेज करें।",
      closingBtn: "व्हाट्सएप पर मैसेज करें",
      plans: [
        {
          id: "online-offline",
          title: "ऑनलाइन एवं ऑफलाइन योग क्लास",
          desc: "मानसून विशेष — बेसिक से एडवांस योग, पावर योग, वेट-लॉस योग, प्राणायाम एवं ध्यान।",
          price: "₹500",
          originalPrice: "₹1,000",
          badge: "50% छूट",
        },
        {
          id: "yoga-class",
          title: "योग क्लास",
          desc: "पावर योग, एडवांस योग, प्राणायाम। सोमवार–शुक्रवार, सुबह 6 बजे व शाम 7 बजे बैच।",
          price: "₹1,500",
          originalPrice: "",
          badge: "",
        },
        {
          id: "personal-classes",
          title: "व्यक्तिगत योग क्लास",
          desc: "डॉ. मोहित कुमार तवर (बी.एच.एम.एस., योग में पीएचडी) के साथ व्यक्तिगत सत्र।",
          price: "₹15,000",
          originalPrice: "",
          badge: "",
        },
        {
          id: "any-condition",
          title: "किसी भी बीमारी हेतु ऑनलाइन योग",
          desc: "कोई भी बीमारी हो, उसके समाधान हेतु व्यक्तिगत ऑनलाइन योग योजना।",
          price: "₹500",
          originalPrice: "",
          badge: "",
        },
        {
          id: "divyanka-academy",
          title: "दिव्यांका आर्ट एकेडमी योग",
          desc: "दिव्यांका आर्ट एकेडमी के सहयोग से योग सत्र।",
          price: "₹1,000",
          originalPrice: "",
          badge: "",
        },
      ],
    },
    reviews: {
      tag: "सत्यापित गूगल समीक्षाएं",
      title: "साधकों की राय",
      subtitle: "डॉ. मोहित तवर की गूगल बिज़नेस प्रोफ़ाइल से वास्तविक समीक्षाएं।",
      ratingValue: "5.0",
      ratingCount: "140 गूगल समीक्षाएं",
      viewAllBtn: "गूगल पर सभी समीक्षाएं पढ़ें",
      ownerReplyLabel: "स्वामी का उत्तर:",
      items: [
        {
          name: "balkrishna karma",
          meta: "लोकल गाइड · 22 समीक्षाएं",
          time: "2 वर्ष पहले",
          text: "सर्वश्रेष्ठ योग क्लास। शिक्षक एक आयुर्वेदिक चिकित्सक हैं, योग में पीएचडी रखते हैं, और गिनीज वर्ल्ड रिकॉर्ड धारक भी हैं। शहर में मिलने वाली सबसे बेहतरीन क्लास। उनकी क्लासेज़ ने मेरे शारीरिक व मानसिक स्वास्थ्य में सुधार लाने में मदद की। पूरी तरह अनुशंसित!",
          ownerReply: "",
        },
        {
          name: "HARSH Maithil",
          meta: "14 समीक्षाएं",
          time: "1 वर्ष पहले",
          text: "योग की अद्भुत तकनीकें — मेरी कमर दर्द पूरी तरह ठीक हो गई। मोहित सर एक शानदार योग शिक्षक हैं, मुझे बहुत पसंद है।",
          ownerReply: "",
        },
        {
          name: "pramila tawar",
          meta: "2 समीक्षाएं",
          time: "2 वर्ष पहले",
          text: "यह योग क्लास मेरे लिए बहुत लाभदायक रही — मेरा शरीर का वज़न कम हुआ और मांसपेशियों की शक्ति बढ़ी। डॉ. मोहित सर का बहुत धन्यवाद, जो योग में गिनीज वर्ल्ड रिकॉर्ड धारक और पीएचडी हैं, बहुत ज्ञानवान व्यक्तित्व।",
          ownerReply: "",
        },
        {
          name: "Aditya Barwal",
          meta: "1 समीक्षा",
          time: "9 माह पहले",
          text: "एमबीबीएस यात्रा के वे 12–13 दिन बहुत लाभदायक और आनंददायक रहे। धन्यवाद।",
          ownerReply: "धन्यवाद",
        },
        {
          name: "Shweta Patidar",
          meta: "7 समीक्षाएं · 1 फोटो",
          time: "9 माह पहले",
          text: "वे इतने अच्छे योग गुरु हैं कि आपको पता ही नहीं चलेगा कि एक घंटा कब बीत गया।",
          ownerReply: "",
        },
        {
          name: "Anup Singh",
          meta: "लोकल गाइड · 63 समीक्षाएं",
          time: "1 वर्ष पहले",
          text: "सर्वश्रेष्ठ योग विशेषज्ञ। स्वास्थ्य के लिए लाभदायक अच्छे पाठ देते हैं। सुसंस्कृत एवं विनम्र।",
          ownerReply: "",
        },
        {
          name: "Dr. Ravikant Gupta",
          meta: "1 समीक्षा",
          time: "1 वर्ष पहले",
          text: "बहुत अच्छा और जानकारीपूर्ण योग चैनल है। मोहित सर यूट्यूब पर मेरे पसंदीदा योग प्रशिक्षक हैं — क्लासेज़ व गतिविधियां बहुत अच्छी हैं।",
          ownerReply: "",
        },
        {
          name: "Vandit Jain",
          meta: "6 समीक्षाएं · 7 फोटो",
          time: "2 वर्ष पहले",
          text: "बहुत अच्छे से योग करवाते हैं। कमर दर्द भी ठीक हो गया मेरा।",
          ownerReply: "",
        },
      ],
    },
    booking: {
      modalBadge: "व्यक्तिगत परामर्श एवं मार्गदर्शन",
      modalTitle: "डॉ. मोहित तवर से परामर्श हेतु आवेदन",
      modalSub: "गर्भाशय भ्रंश (Prolapse), प्रोस्टेट, कमर दर्द अथवा व्यक्तिगत साधना हेतु गोपनीय परामर्श।",
      fullName: "आपका पूरा नाम",
      phone: "व्हाट्सएप संपर्क नंबर",
      city: "शहर एवं राज्य/देश",
      topic: "परामर्श का मुख्य विषय / रोग",
      mode: "परामर्श का प्रकार",
      notes: "रोग के लक्षण अथवा संक्षिप्त विवरण",
      submitBtn: "व्हाट्सएप द्वारा भेजें",
      submitEmailBtn: "अथवा ईमेल करें",
      successTitle: "सप्रेम नमन! आपका अनुरोध तैयार है",
      successDesc: "आपके विवरण सहित व्हाट्सएप खुल गया है — डॉ. मोहित तवर की क्लिनिक टीम तक सीधे पहुंचने हेतु वहां 'Send' दबाएं।",
      modes: ["प्रत्यक्ष परामर्श (क्लिनिक - भोपाल, म.प्र.)", "ऑनलाइन वीडियो परामर्श (देश-विदेश हेतु)"],
      disclaimer: "यह फॉर्म आपातकालीन चिकित्सा सेवा नहीं है। आपातकाल की स्थिति में कृपया तुरंत स्थानीय चिकित्सक से संपर्क करें।",
    },
    footer: {
      tagline: "योग में विद्यावाचस्पति • गिनीज वर्ल्ड रिकॉर्ड धारक • भोपाल, भारत",
      rights: "समस्त वैदिक व यौगिक ज्ञान संपदा शास्त्रीय मर्यादा के साथ सुरक्षित।",
      contact: "क्लिनिक संपर्क: भोपाल, म.प्र.",
      addressLabel: "क्लिनिक",
      phoneLabel: "व्हाट्सएप / फोन",
      emailLabel: "ईमेल",
    },
  },
};

export type Content = (typeof BILINGUAL_CONTENT)["en"];
export type ProtocolItem = Content["protocols"]["items"][number];
